### ISSUE TITLE
checksync is not working if syncrepl binddn contains a space

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-initscript#13]
```
++ echo ': {0}rid="001" provider="ldap://192.168.47.215" type="refreshAndPersist" retry="5 5 300 +" bindmethod="simple" binddn="cn=syncrepl,ou=special users,dc=example,dc=com" credentials="ChangeMe.Please" searchbase="dc=example,dc=com"'
++ sed -e 's/.*binddn[ \t]*=[ \t]*\([^ \t]\+\).*$/\1/'
++ sed -e 's/["]//g'
++ sed -e 's/['\'']//g'
+ PBINDDN=cn=syncrepl,ou=special
```

**Comment by coudot** [comment]
This should work:
```
PBINDDN=$( echo "${PROVIDER[$index]}"  | sed -e 's/.*binddn[ \t]*=[ \t]*"\([^"\t]\+\)".*$/\1/' | sed -e 's/["]//g' | sed -e "s/[']//g" );
```

But we suppose here that value is enclosed in double quotes, this can not always be the case.

**Comment by coudot** [comment]
@davidcoutadeur could we suppose that values are always inside "" ?

**Comment by davidcoutadeur** [comment]
Hi @coudot 

The specification is vague about this point:

> syncrepl  rid=<replica  ID>  provider=ldap[s]://<hostname>[:port]  searchbase=<base DN> [type=refreshOnly|refreshAndPersist] [interval=dd:hh:mm:ss] [retry=[<retry interval> <# of
              retries>]+]  [filter=<filter  str>]  [scope=sub|one|base|subord]  [attrs=<attr   list>]   [exattrs=<attr   list>]   [attrsonly]   [sizelimit=<limit>]   [timelimit=<limit>]
              [schemachecking=on|off]  [network-timeout=<seconds>] [timeout=<seconds>] [bindmethod=simple|sasl] [binddn=<dn>] [saslmech=<mech>] [authcid=<identity>] [authzid=<identity>]
              [credentials=<passwd>]  [realm=<realm>]   [secprops=<properties>]   [keepalive=<idle>:<probes>:<interval>]   [starttls=yes|critical]   [tls_cert=<file>]   [tls_key=<file>]
              [tls_cacert=<file>]          [tls_cacertdir=<path>]          [tls_reqcert=never|allow|try|demand]         [tls_cipher_suite=<ciphers>]         [tls_crlcheck=none|peer|all]
              [tls_protocol_min=<major>[.<minor>]] [suffixmassage=<real DN>] [logbase=<base DN>] [logfilter=<filter str>] [syncdata=default|accesslog|changelog]


Here is my proposal:
it is a perfectly supported feature not to have double quotes.
If we detect a binddn pattern without double quotes, then it is impossible to identify a space in the binddn value from a space separating the next keywords. (or maybe we could if we write a parser defining all accepted keywords, which, in my opinion, is too much work for this script...)
=> so in this situation, assume there is no space in the DN.

In the script we could:
1. detect binddn patterns without double quotes, and surrounds them with double quotes, assuming there is no space:
```
# Surrounds binddn values with double quotes
PBINDDN=$( echo "${PROVIDER[$index]}" | sed -e 's/binddn[ \t]*=[ \t]*\([^" \t]\+\)[ \t]/binddn="\1"/' )
```

2. use the previously proposed pattern matching assuming there are always double quotes:

`PBINDDN=$( echo "${PROVIDER[$index]}"  | sed -e 's/.*binddn[ \t]*=[ \t]*"\([^"\t]\+\)".*$/\1/' | sed -e 's/["]//g' | sed -e "s/[']//g" );`

**Comment by coudot** [comment]
Yes, this seems the best to do, but we can also change the 

So steps:
* 1 - Check if binddn has quotes or not
* 2 - If no quotes, keep current code
* 3 - else, use code that manage quotes

**Comment by davidcoutadeur** [comment]
Ok, seems fine too. You seem to need it soon, so do not hesitate to commit the modification, and I'll take a look
