### ISSUE TITLE
ExecRestart does not exists in systemd

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-initscript#14]
We need to remove ExecRestart as it is not an official systemd command, see https://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by davidcoutadeur** [comment]
Hi @coudot 
I am sorry, I've remove this in master branch 3 month ago, but did not open an issue...
cf:
c79173cdadb16ca7087c150b1b93880a38071a7c

**Comment by coudot** [comment]
Ok so we can close, it will be in next release
