### ISSUE TITLE
Show OpenLDAP version in status

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-initscript#23]
We should be able to see which OpenLDAP version is running. This information may be found in cn=monitor

**Comment by davidcoutadeur** [comment]
done in 4f8bdbd

version is indeed found in cn=monitor, but this is not obvious how to get it:
- we must assume cn=monitor is enabled (disabled by default)
- we must assume a host to connect to
- and mainly, we must assume an anonymous connexion will have sufficient rights to get the info

Thus, best effort is done with cn=monitor, else we get info with slapd -V

IMO, every connected command (check sync, check version,...) should use slap* tools, else we will need to require the admin to configure ldap parameters in `slapd-cli.conf` for online search
