### ISSUE TITLE
Backup error if UMASK not defined

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-initscript#24]
Since #21 fix, we use UMASK var in script, which should be defined in slapd-cli.conf

But after a migration, if slapd-cli.conf was not modified, we get an error:
```
slapd-cli: [INFO] Using /usr/local/openldap/etc/openldap/slapd-cli.conf for configuration
slapd-cli: [INFO] Launching OpenLDAP database backup...
-bash: -c: ligne0: Erreur de syntaxe près du symbole inattendu « && »
-bash: -c: ligne0: `  && /usr/local/openldap/sbin/slapcat -b
```

We should add default values for UMASK in main script.

**Comment by davidcoutadeur** [comment]
Moreover, the umask command has a global range, I think we don't need to set it everywhere.

Thus, 2 things to do:
- add a default value
- factorize the umask commands

**Comment by davidcoutadeur** [comment]
Eventually, it would be too complex to factorize umask, because of commands launched with su.
