### ISSUE TITLE
Create a new 2.3 release

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-initscript#8]
Take these issues into account:
- https://github.com/ltb-project/openldap-initscript/issues/4 -> new initscript
- https://github.com/ltb-project/openldap-initscript/issues/5 -> checksync function

If possible:
- https://github.com/ltb-project/openldap-initscript/issues/2 -> privilege escalation (chown)
- https://github.com/ltb-project/openldap-initscript/issues/3 -> privilege escalation (pid)

**Comment by coudot** [comment]
I think #2 and #3 are not critical (and this is also the case for OpenLDAP team if you read associated ITS). So I will not include them in 2.3.

**Comment by coudot** [comment]
@davidcoutadeur with your last changes I see following issues:
* script name has changed from slapd to slapd-ltb. Most users will be lost if they can do `service slapd restart` any more. Either we keep this name and we change the script name in package, either we change the script name here
* it seems we no more have the possibility to use several init/systemd script in one system. The slapd-cli load CLI_CONF_FILE, we must edit the script to load another file, isn't it? So we can't no more simply create a symlink on slapd script to have for example slapd-meta, etc. We must provide an easy way to have several slapd scripts on one system.

**Comment by coudot** [comment]
@davidcoutadeur I just some changes, tell me if this is ok for you

**Comment by davidcoutadeur** [comment]
@coudot: ok for all changes. Just a remark for this point:

> script name has changed from slapd to slapd-ltb. Most users will be lost if they can do service slapd restart any more. Either we keep this name and we change the script name in package, either we change the script name here

I have made this choice because it is the last point that still prevents our package to be completely compatible with Debian / CentOS OpenLDAP packages. (the systemd / init script has the same name)
Anyway, I don't see how we could both keep the simplicity of `service slapd target` and achieve the compatibility I would like.

**Comment by coudot** [comment]
Thanks for the feedback. I understand the need but I prefer not to change this in a minor release.

We could plan this for OpenLDAP 2.5 (if this is released someday...)
